##  branchLoc-sulkujen väliin tulee alla olevan rivin mukaiset sijainnit kohassa, pilkulla eroteltuna, samalla tavalla kuin _DEFAULT_ rivillä.
##  branchcode, shelving_location, collection_code, sub_location, item.itemtype, item.notforloan-status

1:  branchLoc(POIS)		#REVIEW    #REVIEW
+REVIEW: ref(1)
13: branchLoc(POIS)		#t-mono    #zt-monografi
+t-mono: ref(13)
14: branchLoc(ARCADA,EXAM)		#v-exarb   #v-examensarbete
+v-exarb: ref(14)
15: branchLoc(ARCADA,HAND)		#v-hand    #v-handbiblioteket
+v-hand: ref(15)
16: branchLoc(ARCADA,MONO)		#v-mono    #v-monografi
+v-mono: ref(16)
17: branchLoc(ARCADA,INST)		#v-inst    #v-institutionsexemplar
+v-inst: ref(17)
18: branchLoc(ARCADA,LAG)		#v-lager   #v-lager
+v-lager: ref(18)
19: branchLoc(ARCADA,REF)		#v-ref     #v-referens
+v-ref: ref(19)
20: branchLoc(ARCADA,AV)		#v-av      #v-AV-material
+v-av: ref(20)
25: branchLoc(POIS)		#T-LANEDISK#zt-lånedisk
+T-LANEDISK: ref(25)
24: branchLoc(POIS)		#H-LANEDISK#zh-lånedisk
+H-LANEDISK: ref(24)
26: branchLoc(POIS)		#V-KATAL   #v-katalogisering
+V-KATAL: ref(26)
27: branchLoc(POIS)		#V-LANEDISK#Lånedisken
+V-LANEDISK: ref(27)
28: branchLoc(POIS)		#SELF      #låneautomaten
+SELF: ref(28)
29: branchLoc(ARCADA,KURS)		#v-kurs    #v-kursbok
+v-kurs: ref(29)
34: branchLoc(POIS)		#MAKSU     #Verkkomaksaminen
+MAKSU: ref(34)
31: branchLoc(ARCADA,EBOK)		#v-ebok    #v-elektronisk bok
+v-ebok: ref(31)
30: branchLoc(ARCADA,VID)		#v-video   #v-video
+v-video: ref(30)
32: branchLoc(ARCADA,TIDS)		#v-tidskr  #v-tidskrift
+v-tidskr: ref(32)
33: branchLoc(ARCADA,ETID)		#v-etidskr #Elektronisk tidskrift
+v-etidskr: ref(33)
35: branchLoc(ARCADA,DB)		#v-databas #v-databas
+v-databas: ref(35)

_DEFAULT_: branchLoc(KONVERSIO,KONVERSIO,ERROR,ERROR) #Oletusarvot / paikkaansa löytämättömät
